server:
  port: 8081
  
#spring:
#  datasource:
#    driverClassName: com.mysql.jdbc.Driver
#    url: "jdbc:mysql://localhost:3306/sample"
#    username: "root"
#    password: "root"
##  jpa:
#    hibernate.ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#
spring:
  primary:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/sample"
    username: "root"
    password: "root"
  secondary:
    driverClassName: com.mysql.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/secondarydb"
    username: "root"
    password: "root"
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect


